WebSuperCarros_NET_Framework/SuperCarros2/Controllers/VehiculosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperCarros2;

namespace SuperCarros2.Controllers
{
    public class VehiculosController : Controller
    {
        private DSII_SuperCarrosEntities2 db = new DSII_SuperCarrosEntities2();

        // GET: Vehiculos
        public ActionResult Index()
        {
            var vehiculos = db.Vehiculos.Include(v => v.Brand).Include(v => v.Color).Include(v => v.Model).Include(v => v.Type);
            return View(vehiculos.ToList());
        }
        public ActionResult ImgView()
        {
            var vehiculos = db.Vehiculos.Include(v => v.Brand).Include(v => v.Color).Include(v => v.Model).Include(v => v.Type);
            return View(vehiculos.ToList());
        }

        // GET: Vehiculos/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculos vehiculos = db.Vehiculos.Find(id);
            if (vehiculos == null)
            {
                return HttpNotFound();
            }
            return View(vehiculos);
        }

        // GET: Vehiculos/Create
        public ActionResult Create()
        {
            ViewBag.Brand_Id = new SelectList(db.Brand, "Id", "Name");
            ViewBag.Color_Id = new SelectList(db.Color, "Id", "Name");
            ViewBag.ModeI_Id = new SelectList(db.Model, "Id", "Name");
            ViewBag.Type_Id = new SelectList(db.Type, "Id", "Name");
            return View();
        }

        // POST: Vehiculos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Brand_Id,ModeI_Id,Color_Id,Precio,Combustible,Type_Id,Puertas,Pasajeros,Motor,Transmisión,Año,Imagen,CreatedDate")] Vehiculos vehiculos, HttpPostedFileBase imgUpload)
        {
            if (ModelState.IsValid)
            {
                vehiculos.Id = Guid.NewGuid().ToString();
                vehiculos.CreatedDate = DateTime.Now;
                if(imgUpload != null)
                {
                    string imgUrl = System.IO.Path.GetFileName(imgUpload.FileName);
                    string pathUrl = System.IO.Path.Combine(Server.MapPath("/public/vehiculos_img"), imgUrl);

                    imgUpload.SaveAs(pathUrl);
                    vehiculos.Imagen = imgUrl;
                }

                db.Vehiculos.Add(vehiculos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Brand_Id = new SelectList(db.Brand, "Id", "Name", vehiculos.Brand_Id);
            ViewBag.Color_Id = new SelectList(db.Color, "Id", "Name", vehiculos.Color_Id);
            ViewBag.ModeI_Id = new SelectList(db.Model, "Id", "Name", vehiculos.ModeI_Id);
            ViewBag.Type_Id = new SelectList(db.Type, "Id", "Name", vehiculos.Type_Id);
            return View(vehiculos);
        }

        // GET: Vehiculos/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculos vehiculos = db.Vehiculos.Find(id);
            if (vehiculos == null)
            {
                return HttpNotFound();
            }
            ViewBag.Brand_Id = new SelectList(db.Brand, "Id", "Name", vehiculos.Brand_Id);
            ViewBag.Color_Id = new SelectList(db.Color, "Id", "Name", vehiculos.Color_Id);
            ViewBag.ModeI_Id = new SelectList(db.Model, "Id", "Name", vehiculos.ModeI_Id);
            ViewBag.Type_Id = new SelectList(db.Type, "Id", "Name", vehiculos.Type_Id);
            return View(vehiculos);
        }

        // POST: Vehiculos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Brand_Id,ModeI_Id,Color_Id,Precio,Combustible,Type_Id,Puertas,Pasajeros,Motor,Transmisión,Año,Imagen,CreatedDate")] Vehiculos vehiculos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehiculos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Brand_Id = new SelectList(db.Brand, "Id", "Name", vehiculos.Brand_Id);
            ViewBag.Color_Id = new SelectList(db.Color, "Id", "Name", vehiculos.Color_Id);
            ViewBag.ModeI_Id = new SelectList(db.Model, "Id", "Name", vehiculos.ModeI_Id);
            ViewBag.Type_Id = new SelectList(db.Type, "Id", "Name", vehiculos.Type_Id);
            return View(vehiculos);
        }

        // GET: Vehiculos/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculos vehiculos = db.Vehiculos.Find(id);
            if (vehiculos == null)
            {
                return HttpNotFound();
            }
            return View(vehiculos);
        }

        // POST: Vehiculos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Vehiculos vehiculos = db.Vehiculos.Find(id);
            db.Vehiculos.Remove(vehiculos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSuperCarros_NET_Framework/SuperCarros2/Views/Vehiculos/Create.cshtml
@model SuperCarros2.Vehiculos

@{
    ViewBag.Title = "Create";
}

<h2>Agregar Vehiculos</h2>


@using (Html.BeginForm("Create", "Vehiculos", FormMethod.Post, new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Type_Id, "Type_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Type_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Type_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Brand_Id, "Brand_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Brand_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Brand_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModeI_Id, "ModeI_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ModeI_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ModeI_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Color_Id, "Color_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Color_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Color_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
               
                <label class = "control-label col-md-2">Precio<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Combustible<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Combustible, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Combustible, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
       


        <div class="col-lg-6">
            <div class="form-group">
                <label class="control-label col-md-2">Puertas<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Puertas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Puertas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Pasajeros<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Pasajeros, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pasajeros, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Motor<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Motor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Motor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Transmisión<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Transmisión, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Transmisión, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Año<span style="color:red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="imgUpload" id="imgUpload" class="form-control"/>
                    @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>
    </div>

        
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSuperCarros_NET_Framework/SuperCarros2/Views/Vehiculos/Delete.cshtml
@model SuperCarros2.Vehiculos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehiculos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Combustible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Combustible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puertas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puertas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pasajeros)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pasajeros)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Transmisión)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Transmisión)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Año)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Año)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebSuperCarros_NET_Framework/SuperCarros2/Views/Vehiculos/Details.cshtml
@model SuperCarros2.Vehiculos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehiculos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Combustible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Combustible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puertas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puertas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pasajeros)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pasajeros)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Transmisión)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Transmisión)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Año)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Año)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebSuperCarros_NET_Framework/SuperCarros2/Views/Vehiculos/Edit.cshtml
@model SuperCarros2.Vehiculos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Brand_Id, "Brand_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Brand_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Brand_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModeI_Id, "ModeI_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModeI_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModeI_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color_Id, "Color_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Color_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Color_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Combustible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Combustible, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Combustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type_Id, "Type_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Puertas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Puertas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Puertas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pasajeros, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pasajeros, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pasajeros, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Motor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transmisión, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Transmisión, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Transmisión, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSuperCarros_NET_Framework/SuperCarros2/Views/Vehiculos/ImgView.cshtml
@model IEnumerable<SuperCarros2.Vehiculos>

@{
    ViewBag.Title = "ImgView";
}

<h2>Carros disponibles</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3">
            <img src="~/public/vehiculos_img/@(string.IsNullOrEmpty(item.Imagen)? "CarIconRed2.png" : item.Imagen)"
                 style="height:100px ; width:100px" />
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </div>

        

    }
</div>

WebSuperCarros_NET_Framework/SuperCarros2/Views/Vehiculos/Index.cshtml
@model IEnumerable<SuperCarros2.Vehiculos>

@{
    ViewBag.Title = "Index";
}

<h2>Lista vehiculos creados</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>
        <th>
            Precio (US$)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Combustible)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Puertas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pasajeros)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Motor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Transmisión)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Año)
        </th>

        <th>
            Fecha de creación
        </th>
        <th>
            Marca
        </th>
        <th>
            Color
        </th>
        <th>
            Modelo
        </th>
        <th>
            Tipo
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="~/public/vehiculos_img/@(string.IsNullOrEmpty(item.Imagen)? "CarIconRed2.png" : item.Imagen)" style="height:100px ; width:100px"/>
           
        </td>

        <td>
            <span style="color:forestgreen">@item.Precio</span>
            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Combustible)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Puertas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pasajeros)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Motor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Transmisión)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Año)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>